# =============================================================================
# PROMETHEUS CONFIGURATION FOR GARAGEREG
# Monitoring and metrics collection
# =============================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'garagereg-monitor'
    environment: 'development'

# =============================================================================
# RULE FILES
# =============================================================================
rule_files:
  - "/etc/prometheus/rules/*.yml"

# =============================================================================
# ALERTING
# =============================================================================
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# =============================================================================
# SCRAPE CONFIGURATIONS
# =============================================================================
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # PostgreSQL metrics (requires postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Redis metrics (requires redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    metrics_path: /metrics

  # GarageReg Backend API
  - job_name: 'garagereg-backend'
    static_configs:
      - targets: ['backend:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    scheme: http

  # Node Exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # BlackBox Exporter for HTTP monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://admin.garagereg.local
        - https://api.garagereg.local/health
        - https://traefik.garagereg.local
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# =============================================================================
# REMOTE WRITE (for production)
# =============================================================================
# remote_write:
#   - url: "https://your-remote-prometheus-endpoint/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"

# =============================================================================
# STORAGE CONFIGURATION
# =============================================================================
# storage:
#   tsdb:
#     retention.time: 15d
#     retention.size: 10GB