# Traefik dynamic configuration
# This file contains dynamic configuration for Traefik

# TLS Configuration
tls:
  options:
    default:
      sslProtocols:
        - "TLSv1.2"
        - "TLSv1.3"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"

# HTTP Configuration
http:
  # Global middlewares
  middlewares:
    # Security headers
    secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
          - PATCH
        accessControlAllowOriginList:
          - http://localhost:3000
          - http://localhost:3001
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 31536000
        stsPreload: true

    # Rate limiting
    rate-limit:
      rateLimit:
        average: 100
        period: "1m"
        burst: 200

    # CORS
    cors:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-Requested-With"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowOriginList:
          - "http://localhost:3000"
          - "http://localhost:3001"
        accessControlMaxAge: 100

  # Services
  services:
    api:
      loadBalancer:
        healthCheck:
          path: /healthz
          interval: "30s"
          timeout: "10s"
        servers:
          - url: "http://api:8000"

    web-admin:
      loadBalancer:
        servers:
          - url: "http://web-admin:3000"